/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import AccesoDatos.ADBanco;
import Entidades.Banco;
import Recaudacion.Modelos.ModeloTablaBancos;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Raul
 */
public class gestBanco extends javax.swing.JInternalFrame {
    
    private ModeloTablaBancos mtb = new ModeloTablaBancos();
    ADBanco adBanco = new ADBanco();
    String FaltaLlenar = "";
    int codigo;
    private Banco actual;
    
    public gestBanco() {
        initComponents();

        InicioComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtSiglas = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBancos = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gestión de Bancos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de Banco", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel11.setText("Razon Social");

        jLabel12.setText("Siglas");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addContainerGap())
        );

        jLabel13.setText("Buscar");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Bancos"));

        tblBancos.setModel(this.mtb);
        tblBancos.getTableHeader().setReorderingAllowed(false);
        tblBancos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBancosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBancos);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel13)
                .addGap(12, 12, 12)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel13))
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     private void InicioComponentes(){
                        
        Actualizar_Tabla();        
        btnModificar.setEnabled(false);
        btnGuardar.setVisible(false);
        
    }
    
    private void Actualizar_Tabla(){                    
        
        List<Banco> ListB;
        try {
            ListB = adBanco.ListarTabla();
            this.mtb.setCuentaB(ListB);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            adBanco = null;
        }
       
    }
    
    public void DesabilitarCampos(){
        txtRazonSocial.setEnabled(false);
        txtSiglas.setEnabled(false);
        
    }
    
    public void HabilitarCampos(){
        txtRazonSocial.setEnabled(true);
        txtSiglas.setEnabled(true);
            
    }
    
    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // Boton de la formulario GESTIONAR BANCO
        HabilitarCampos();
        Actualizar_Tabla();
        btnRegistrar.setEnabled(true);
        btnGuardar.setVisible(false);
        btnModificar.setVisible(true);
        btnModificar.setEnabled(false);
        txtRazonSocial.setText("");
        txtSiglas.setText("");
        txtRazonSocial.requestFocus();
       
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (Validacion() == true) {

            Banco objBanco;

            objBanco = new Banco();
            objBanco.setRazonSocial(txtRazonSocial.getText());
            objBanco.setSiglas(txtSiglas.getText());
            adBanco = new ADBanco();
            try {
                if (adBanco.registrar(objBanco)) {
                    JOptionPane.showMessageDialog(this, "Datos de Banco Registrados");
                    DesabilitarCampos();
                    btnGuardar.setVisible(false);
                    btnModificar.setEnabled(true);
                    btnRegistrar.setEnabled(false);
                    Actualizar_Tabla();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al Guardar los Datos");
                }
            } catch (Exception e) {
                 JOptionPane.showMessageDialog(this, e.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(null, FaltaLlenar);
            FaltaLlenar = "";
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void tblBancosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBancosMouseClicked
        DesabilitarCampos();
        btnRegistrar.setEnabled(false);
        btnModificar.setVisible(true);
        btnModificar.setEnabled(true);
        btnGuardar.setVisible(false);

        int pos = this.tblBancos.getSelectedRow();

        if (pos > -1) {
            this.actual = this.mtb.getBanco(pos);
            this.presentarDatos();

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un curso");
        }
    }//GEN-LAST:event_tblBancosMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        btnModificar.setVisible(false);
        btnGuardar.setVisible(true);
        HabilitarCampos();
        txtBuscar.setEnabled(false);
        
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int opt = JOptionPane.showConfirmDialog(this,"¿Esta Seguro de Modificar los Datos?","", JOptionPane.YES_NO_OPTION);
        Banco b;
        b = new Banco();
        b.setCodigo(this.actual.getCodigo());
        b.setRazonSocial(txtRazonSocial.getText());
        b.setSiglas(txtSiglas.getText());
        adBanco = new ADBanco();        
        if (opt == JOptionPane.YES_OPTION) {
            if (Validacion()== true) {
                try {                
                    adBanco.modificar(b);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
                
            } else {
                JOptionPane.showMessageDialog(null, FaltaLlenar);
            }                
            Actualizar_Tabla();
        }   
        btnGuardar.setVisible(false);
        btnModificar.setVisible(true);
        DesabilitarCampos();
    }//GEN-LAST:event_btnGuardarActionPerformed

     private void presentarDatos() {
        adBanco = new ADBanco();
        try {
            this.actual = adBanco.leer(this.actual);
            if (this.actual != null) {
                this.txtRazonSocial.setText(this.actual.getRazonSocial());
                this.txtSiglas.setText(this.actual.getSiglas());                

            } else {
                JOptionPane.showMessageDialog(null, "No se encontro");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            adBanco = null;
        }
    }
    
     public boolean Validacion(){
        
        boolean Completo = true;
        if (this.txtRazonSocial.getText().isEmpty()) {
                FaltaLlenar += "ERROR : CAMPO RAZON SOCIAL ESTA VACIO\n";
                Completo = false;
        }
        if (this.txtSiglas.getText().isEmpty()) {
                FaltaLlenar += "ERROR : CAMPO SIGLAS ESTA VACIO\n";
                Completo = false;
        }
       
        return Completo;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBancos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtSiglas;
    // End of variables declaration//GEN-END:variables
}
