/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import AccesoDatos.ADBanco;
import AccesoDatos.ADCuentaBancaria;
import Entidades.Banco;
import Entidades.CuentaBancaria;
import Recaudacion.Modelos.ModeloComboBanco;
import Recaudacion.Modelos.ModeloTablaCuentas;
import java.util.Calendar;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Raul
 */
public class gestCuentaBancaria extends javax.swing.JInternalFrame {

    private ModeloTablaCuentas mtc = new ModeloTablaCuentas();
    ADCuentaBancaria adCuentaBanc = new ADCuentaBancaria();
    ADBanco adBanco = new ADBanco();
    String FaltaLlenar = "";
    int codigo;
    private CuentaBancaria actual;

    public gestCuentaBancaria() {
        initComponents();
        InicioComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtNumCuenta = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        dtpFechaApert = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        txtDenominacion = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtMontoIni = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtCodInterBancario = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cboBancos = new javax.swing.JComboBox();
        btnNuevo = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCuentasBancarias = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Cuenta Bancaria", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel14.setText("Numero");

        jLabel15.setText("Fecha Apertura");

        dtpFechaApert.setDateFormatString("dd-MM-yyyy");
        dtpFechaApert.setMaxSelectableDate(new java.util.Date(253370786461000L));
        dtpFechaApert.setMinSelectableDate(new java.util.Date(-62135747939000L));

        jLabel16.setText("Denominación");

        jLabel17.setText("Monto Inicial");

        jLabel18.setText("Codigo Interbancario");

        jLabel19.setText("Banco");

        cboBancos.setModel(listarBancos());

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/new.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/check.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDenominacion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(10, 10, 10)
                        .addComponent(txtCodInterBancario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMontoIni, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtpFechaApert, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboBancos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrar)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtDenominacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtCodInterBancario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dtpFechaApert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMontoIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboBancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnRegistrar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Cuentas Bancarias"));

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        tblCuentasBancarias.setModel(this.mtc);
        tblCuentasBancarias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCuentasBancariasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCuentasBancarias);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/save.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/edit.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel20.setText("Buscar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnModificar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicioComponentes() {

        Actualizar_Tabla();
        dtpFechaApert.setDate(Calendar.getInstance().getTime());
        dtpFechaApert.setEnabled(true);
        btnModificar.setEnabled(false);
        btnGuardar.setVisible(false);

        cboBancos.setSelectedIndex(-1);

    }

    public void DesabilitarCampos() {
        txtNumCuenta.setEnabled(false);
        txtDenominacion.setEnabled(false);
        txtCodInterBancario.setEnabled(false);
        txtMontoIni.setEnabled(false);
        cboBancos.setEnabled(false);
        dtpFechaApert.setEnabled(false);
    }

    public void HabilitarCampos() {
        txtNumCuenta.setEnabled(true);
        txtDenominacion.setEnabled(true);
        txtCodInterBancario.setEnabled(true);
        txtMontoIni.setEnabled(true);
        cboBancos.setEnabled(true);
        dtpFechaApert.setEnabled(true);
    }

    private void Actualizar_Tabla() {
        List<CuentaBancaria> CB;

        try {
            CB = adCuentaBanc.ListarTabla();
            this.mtc.setCuentaB(CB);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            adCuentaBanc = null;
        }
    }

    public boolean Validacion() {

        boolean Completo = true;
        if (this.txtNumCuenta.getText().isEmpty()) {
            FaltaLlenar += "ERROR : CAMPO Numero de Cuenta ESTA VACIO\n";
            Completo = false;
        }
        if (this.cboBancos.getSelectedIndex() == -1) {
            FaltaLlenar += "ERROR : CAMPO Banco ESTA VACIO\n";
            Completo = false;
        }
        if (this.txtCodInterBancario.getText().isEmpty()) {
            FaltaLlenar += "ERROR : CAMPO Codigo Interbancario ESTA VACIO\n";
            Completo = false;
        }
        if (this.dtpFechaApert.getDate() == null) {
            FaltaLlenar += "ERROR : CAMPO FECHA APERTURA ESTA VACIO\n";
            Completo = false;
        }
        if (this.txtMontoIni.getText().isEmpty()) {
            FaltaLlenar += "ERROR : CAMPO MONTO INICIAL ESTA VACIO\n";
            Completo = false;
        }
        if (this.txtDenominacion.getText().isEmpty()) {
            FaltaLlenar += "ERROR : CAMPO DENOMINACION ESTA VACIO\n";
            Completo = false;
        }

        return Completo;
    }

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        HabilitarCampos();
        Actualizar_Tabla();
        btnRegistrar.setEnabled(true);
        btnGuardar.setVisible(false);
        btnModificar.setVisible(true);
        btnModificar.setEnabled(false);

        txtNumCuenta.setText("");
        txtCodInterBancario.setText("");
        cboBancos.setSelectedIndex(-1);
        txtDenominacion.setText("");
        dtpFechaApert.setDate(Calendar.getInstance().getTime());
        txtMontoIni.setText("");
        txtNumCuenta.requestFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (Validacion() == true) {

            CuentaBancaria objCB;
            ModeloComboBanco mcb;
            mcb = (ModeloComboBanco) this.cboBancos.getModel();

            java.sql.Date FechaApert = new java.sql.Date(dtpFechaApert.getDate().getTime());

            objCB = new CuentaBancaria();
            objCB.setNumero(txtNumCuenta.getText());
            objCB.setFechaApertura(FechaApert);
            objCB.setDenominacion(txtDenominacion.getText());
            objCB.setMontoInicial(Double.parseDouble(txtMontoIni.getText()));
            objCB.setCodigoInterbancario(txtCodInterBancario.getText());
            objCB.setBanco(mcb.getBanco().get(this.cboBancos.getSelectedIndex()));

            adCuentaBanc = new ADCuentaBancaria();
            try {
                if (adCuentaBanc.RegistrarCuentaB(objCB)) {
                    JOptionPane.showMessageDialog(this, "Datos de Cuenta Bancaria Registrados");
                    Actualizar_Tabla();
                    DesabilitarCampos();
                    btnGuardar.setVisible(false);
                    btnModificar.setEnabled(true);
                    btnRegistrar.setEnabled(false);

                } else {
                    JOptionPane.showMessageDialog(this, "Error al Guardar los Datos");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(null, FaltaLlenar);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        btnModificar.setVisible(false);
        btnGuardar.setVisible(true);
        HabilitarCampos();
        txtBuscar.setEnabled(false);
        txtMontoIni.setEnabled(false);

    }//GEN-LAST:event_btnModificarActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void tblCuentasBancariasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCuentasBancariasMouseClicked
        DesabilitarCampos();
        btnRegistrar.setEnabled(false);
        btnModificar.setVisible(true);
        btnModificar.setEnabled(true);
        btnGuardar.setVisible(false);

        int pos = this.tblCuentasBancarias.getSelectedRow();

        if (pos > -1) {
            this.actual = this.mtc.getCuentaB(pos);
            this.presentarDatos();

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un curso");
        }
    }//GEN-LAST:event_tblCuentasBancariasMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int opt = JOptionPane.showConfirmDialog(this, "¿Esta Seguro de Modificar los Datos?", "", JOptionPane.YES_NO_OPTION);

        CuentaBancaria objCB;
        ModeloComboBanco mcb;
        mcb = (ModeloComboBanco) this.cboBancos.getModel();

        java.sql.Date FechaApert = new java.sql.Date(dtpFechaApert.getDate().getTime());

        objCB = new CuentaBancaria();
        objCB.setCodigo(this.actual.getCod());
        objCB.setNumero(txtNumCuenta.getText());
        objCB.setFechaApertura(FechaApert);
        objCB.setDenominacion(txtDenominacion.getText());
        objCB.setMontoInicial(Double.parseDouble(txtMontoIni.getText()));
        objCB.setCodigoInterbancario(txtCodInterBancario.getText());
        objCB.setBanco(mcb.getBanco().get(this.cboBancos.getSelectedIndex()));

        adCuentaBanc = new ADCuentaBancaria();

        if (opt == JOptionPane.YES_OPTION) {
            if (Validacion() == true) {
                try {
                    adCuentaBanc.modificar(objCB);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }

            } else {
                JOptionPane.showMessageDialog(null, FaltaLlenar);
            }
            Actualizar_Tabla();
        }
        btnGuardar.setVisible(false);
        btnModificar.setVisible(true);
        DesabilitarCampos();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void presentarDatos() {
        adCuentaBanc = new ADCuentaBancaria();
        ModeloComboBanco mcb;

        try {
            this.actual = adCuentaBanc.leer(this.actual);
            if (this.actual != null) {
                mcb = (ModeloComboBanco) this.cboBancos.getModel();
                mcb.seleccionarBanco(this.actual.getBanco());
                this.txtNumCuenta.setText(this.actual.getNumero());
                this.dtpFechaApert.setDate(this.actual.getFechaApertura());
                this.txtDenominacion.setText(this.actual.getDenominacion());
                this.txtMontoIni.setText(String.valueOf(this.actual.getMontoInicial()));
                this.txtCodInterBancario.setText(this.actual.getCodigoInterbancario());

            } else {
                JOptionPane.showMessageDialog(null, "No se encontro");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            adCuentaBanc = null;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox cboBancos;
    private com.toedter.calendar.JDateChooser dtpFechaApert;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCuentasBancarias;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodInterBancario;
    private javax.swing.JTextField txtDenominacion;
    private javax.swing.JTextField txtMontoIni;
    private javax.swing.JTextField txtNumCuenta;
    // End of variables declaration//GEN-END:variables

    private ComboBoxModel listarBancos() {

        ModeloComboBanco mcb = new ModeloComboBanco();
        List<Banco> tipos;

        try {
            tipos = adBanco.listar();
            mcb.setTipos(tipos);
            mcb.setSelectedItem(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            adBanco = null;
        }
        return mcb;
    }
}
