/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import AccesoDatos.ADBanco;
import AccesoDatos.ADCaja;
import AccesoDatos.ADRecaudacion;
import Entidades.Recaudacion;
import Entidades.Caja;
import Entidades.Usuario;
import Recaudacion.modelos.ModeloComboCaja;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Raul
 */
public class JFNumCaja extends javax.swing.JFrame {

    /**
     * Creates new form JFNumCaja
     */
    ADCaja adCaja = new ADCaja();
    ADRecaudacion adRecaudacion = new ADRecaudacion();
    public JFNumCaja() {
        initComponents();       
        this.setLocationRelativeTo(null);
        //lblcodUsuario.setVisible(false);
        
      
     }

     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cboCajas = new javax.swing.JComboBox();
        btnCancelar = new javax.swing.JButton();
        btnIniciarRecaudacion = new javax.swing.JButton();
        lblcodUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNombUsuario.setText("Nombre del Usuario");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Bienvenido:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Numero de Caja"));

        cboCajas.setModel(this.listarCajas());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(cboCajas, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboCajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btnCancelar.setText("Cancelar");

        btnIniciarRecaudacion.setText("Iniciar Recaudacion");
        btnIniciarRecaudacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarRecaudacionActionPerformed(evt);
            }
        });

        lblcodUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblcodUsuario.setText("codUsuario");
        lblcodUsuario.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcodUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNombUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIniciarRecaudacion)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblcodUsuario))
                .addGap(18, 18, 18)
                .addComponent(lblNombUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciarRecaudacion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarRecaudacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarRecaudacionActionPerformed
         if (this.cboCajas.getSelectedIndex() != -1) {
           
           Recaudacion objRec;
           ModeloComboCaja mcc;
           mcc = (ModeloComboCaja) this.cboCajas.getModel();
           
           objRec = new Recaudacion();
           objRec.setCodigoPersona(Integer.parseInt(lblcodUsuario.getText()));
           objRec.setCaja(mcc.getTipos().get(this.cboCajas.getSelectedIndex()));
           
           adRecaudacion = new ADRecaudacion();
             try {
                  if (adRecaudacion.registrar(objRec)) {
                    JOptionPane.showMessageDialog(this, "Recaudacion Inicializada");
                    JFPrincipal from = new JFPrincipal();
                    Recaudacion objR;
                    objR = new Recaudacion();
                    objR = adRecaudacion.leer(objRec);
                    from.lblcodRecaudacion.setText(String.valueOf(objR.getCodigo()));
                    from.setVisible(true);
                    this.setVisible(false);

                } else {
                    JOptionPane.showMessageDialog(this, "Error al Iniciar Recaudacion");
                }
             } catch (Exception e) {
                 JOptionPane.showMessageDialog(this, e.getMessage());
             }
             
        }else{
              JOptionPane.showMessageDialog(null, "Escoja Numero de Caja");
        }
    }//GEN-LAST:event_btnIniciarRecaudacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFNumCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFNumCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFNumCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFNumCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFNumCaja().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIniciarRecaudacion;
    private javax.swing.JComboBox cboCajas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblNombUsuario;
    public javax.swing.JLabel lblcodUsuario;
    // End of variables declaration//GEN-END:variables
    private ComboBoxModel listarCajas() {

        ModeloComboCaja mcc = new ModeloComboCaja();
        List<Caja> tipos;

        try {
            tipos = adCaja.listar();
            mcc.setTipos(tipos);
            mcc.setSelectedItem(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            adCaja = null;
        }
        return mcc;
    }

}
